version: "3"

services:
  app:
    build:
      context: .
    image: node_app:1.0.0
    env_file: .env
    volumes:
      - ./:/opt/app
    ports:
      - "12345:12345"

  redis:
    image: redis:4.0.8
    volumes:
      - redis

  db:
    image: mongo:3.6.2
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"

volumes:
  db: